$(function(){
	//--
	//$('.nav').find('li:last').css('background','none');
	$('.indexPart_01').find('li:last').css('border','0px');
	$('.sideNav>ul>li:last').css('background','none');
	$('.sideNav').find('.list').find('li:last').css('background','none');
	$('.news').find('.list1').find('li:last').css('border','0px');
	$('.news').find('.list').find('li:last').css('border','0px');
	//--底部网站地图
	$('.footMapA').toggle(
	    function(){
			$('.footNav').animate({height: 293}, "slow");
			$('.footDiv').addClass('footDivNow');
			},
		function(){
			$('.footNav').animate({height: 0}, "slow");
			$('.footDiv').removeClass('footDivNow');
			}
	)
	//--荣誉列表
	$('.Honor').find('li').hover(
	    function(){
			$(this).addClass('liNow');
			},
		function(){
			$(this).removeClass('liNow');
			}
	)
	//--荣誉详情页
	$('.HonorShow').find('.rightBtn').click(function(){
		imgScrollRight2($('.HonorShow').find('.list'),$('.HonorShow').find('li').length-4,145,0);
		})
	$('.HonorShow').find('.leftBtn').click(function(){
		imgScrollLeft2($('.HonorShow').find('.list'),$('.HonorShow').find('li').length-4,145,0);
		})	
	$('.HonorShow').find('li').click(function(){
		$('.HonorShow').find('.bigImg').find('img').attr('src',$(this).find('img').attr('src'));
		})
	//--图片变灰
	if($('.grayImg').length>0){
	   grayscale($('.grayImg'));
	}		
	//--案例
	$('.caseList').find('.grayImg:first').fadeOut(100);
	$('.caseList').find('li').each(function(i){
		$(this).click(function(){
			$('.caseList').find('.grayImg').show();
			$(this).find('.grayImg').fadeOut(100);
			$('.caseShow').load('./?caseshow/varid/'+$(this).attr('ajaxId')+'.html');
			})
		})
	$('.caseList').find('.rightBtn').click(function(){
		imgScrollRight2($('.caseList').find('.list'),$('.caseList').find('li').length-4,170,0);
		})
	$('.caseList').find('.leftBtn').click(function(){
		imgScrollLeft2($('.caseList').find('.list'),$('.caseList').find('li').length-4,170,0);
		})
	//--工作
	var	jobNow=100;
	$('.job').find('li').each(function(i){
		$(this).find('.name').click(function(){
			if(i==jobNow){
				jobNow=100;
				$('.job').find('li').removeClass('liNow');
				}else{
					jobNow=i;
					$('.job').find('li').removeClass('liNow');
					$('.job').find('li').eq(jobNow).addClass('liNow');
					}
			})
		})
	//--历史
	$('.History').find('li').hover(
	    function(){
			$(this).addClass('liNow');
			},
		function(){
			$(this).removeClass('liNow');
			}
	)
	$('.History').find('.rightBtn').click(function(){
		$('.History').find('.list').animate({scrollTop: $('.History').find('.list').scrollTop()+100}, "slow");
		})	
	$('.History').find('.leftBtn').click(function(){
		$('.History').find('.list').animate({scrollTop: $('.History').find('.list').scrollTop()-100}, "slow");
		})		
	//--首页解决方案
	var indexPart_03Now=0;
	$('.indexPart_03').find('li:first').css('left',0);
	$('.indexPart_03').find('.rightBtn').click(function(){
		$('.indexPart_03').find('li').each(function(i){
			if(i!=indexPart_03Now){
				$(this).css('left',250);
				}
			})
		$('.indexPart_03').find('li').eq(indexPart_03Now).animate({left:-250},"slow");
		if(indexPart_03Now<$('.indexPart_03').find('li').length-1){
			indexPart_03Now++;
			}else{
				indexPart_03Now=0;
				}
		$('.indexPart_03').find('li').eq(indexPart_03Now).animate({left:0},"slow");	
		})	
	$('.indexPart_03').find('.leftBtn').click(function(){
		$('.indexPart_03').find('li').each(function(i){
			if(i!=indexPart_03Now){
				$(this).css('left',-250);
				}
			})
		$('.indexPart_03').find('li').eq(indexPart_03Now).animate({left:250},"slow");
		if(indexPart_03Now>0){
			indexPart_03Now--;
			}else{
				indexPart_03Now=$('.indexPart_03').find('li').length-1;
				}
		$('.indexPart_03').find('li').eq(indexPart_03Now).animate({left:0},"slow");	
		})	
	//--首页焦点图
	var indexFlashTime;
	if($('.indexFlash').length>0){
		indexFlashFun2();
		$(window).resize(function(){
			indexFlashFun2();
			})
		if($('.indexFlash').find('li').length>1){
			    indexFlashTime = setInterval("indexFlashFun()",5000);
			}else{
				$('.indexFlash').find('.rightBtn').hide();
				$('.indexFlash').find('.leftBtn').hide();
				}
		$('.indexFlash').find('li:first').find('a').css('left',0);	
		}
	$('.indexFlash').find('.rightBtn').click(function(){
		clearInterval(indexFlashTime);
		$('.indexFlash').find('li').each(function(i){
			if(i!=indexFlashNow){
				$(this).find('a').css('left',"100%");
				}
			})
		$('.indexFlash').find('li').eq(indexFlashNow).find('a').animate({left:"-100%"},"slow");
		if(indexFlashNow<$('.indexFlash').find('li').length-1){
			indexFlashNow++;
			}else{
				indexFlashNow=0;
				}
		$('.indexFlash').find('li').eq(indexFlashNow).find('a').animate({left:0},"slow");	
		indexFlashTime = setInterval("indexFlashFun()",5000);
		})	
	$('.indexFlash').find('.leftBtn').click(function(){
		clearInterval(indexFlashTime);
		$('.indexFlash').find('li').each(function(i){
			if(i!=indexFlashNow){
				$(this).find('a').css('left',"-100%");
				}
			})
		$('.indexFlash').find('li').eq(indexFlashNow).find('a').animate({left:"100%"},"slow");
		if(indexFlashNow>0){
			indexFlashNow--;
			}else{
				indexFlashNow=$('.indexFlash').find('li').length-1;
				}
		$('.indexFlash').find('li').eq(indexFlashNow).find('a').animate({left:0},"slow");	
		indexFlashTime = setInterval("indexFlashFun()",5000);
		})	
	//--下拉菜单
	var top_nav;
	$('.headDiv').find('li').each(function(i){
		$(this).hover(
		  function(){
			  clearTimeout(top_nav);
			  $('.sNav').hide();
			  $('.sNav').eq(i).width($(this).width());
			  $('.sNav').eq(i).css('left',$(this).offset().left-1);
			  $('.sNav').eq(i).show();
			  $('.headDiv').find('li').find('a').removeClass('aNow1');
			  $('.headDiv').find('li').eq(i).find('a').addClass('aNow1');
			  },
		  function(){
			top_nav=setTimeout(function(){
				$('.sNav').hide();
				$('.headDiv').find('li').find('a').removeClass('aNow1');
				},500);
			}
		)
		})
	$('.sNav').each(function(i){	
	$(this).hover(
	    function(){
			$('.headDiv').find('li').eq(i).find('a').addClass('aNow1');
			clearTimeout(top_nav);
			$(this).show();
			},
		function(){
			top_nav=setTimeout(function(){
				$('.sNav').hide();
				$('.headDiv').find('li').find('a').removeClass('aNow1');
				},500);
			}
	)
	})				
	//
	})